const when_you = {
  first: "First Read Me",
  bad: "Have a Bad Day",
  miss: "Miss Me",
  laugh: "Need to Laugh",
  sleep: "Can't Sleep",
  insecure: "are Feeling Insecure",
  happy: "Are Happy",
  lonely: "Feel Lonely",
  worried: "Are Worried About Something",
  pep: "Need a Pep Talk",
  birthday: "Have a Birthday",
  christmas: "Have a Merry Christmas",
  valentines: "Have a Happy Valentine's Day",
  new_year: "Have a Happy New Year",
  give_up: "Feel Like Giving Up",
  frustrated: "Are Frustrated with Work",
  sick: "Are Sick",
  canceled: "See Our Plans Canceled",
  doubt: "Doubt Yourself",
  hug: "Need a Hug",
  compliment: "Need a Compliment",
  mistake: "Have Made a Mistake",
  motivation: "Need Motivation",
  movie: "Need Movie Recommendations",
  excited: "Are Excited About Something",
  bored: "Are Bored",
  big_decision: "Need to Make a Big Decision",
  social_media: "Are Sick of Social Media",
  angry: "Are Angry",
  broken: "Get Your Heart Broken",
  argument: "Are in an Argument with Me",
  memory: "Want to Know My Favorite Memory of Us",
  speak: "Haven't Spoken to Me in a While",
  phone: "See Me Not Answering My Phone",
  goals: "Feel Like Giving Up on Your Goals",
  embarass: "Do Something Embarrassing",
  lose: "Lose Someone or Something Precious To You",
  presence: "Wish I Was There",
  cry: "Feel Like Crying",
  proud: "Do Something You're Proud Of",
  reminisce: "Want to Reminisce",
  loved: "Need to Feel Loved",
  you_angry_me: "Are Angry at Me",
  me_angry_you: "See Me Angry at You",
  new: "Do Something New",
  anniversary: "Know It's Our Anniversary",
  celebration: "Are Celebrating an Achievement",
  music: "Need Music Recommendations",
  occasion: "Have a Special Occasion I can't Attend",
  remind_you: "Want to Learn About the Things that Remind Me of You",
  food: "Need Food Recommendations",
  vacation: "Need a Vacation",
  fitness: "Need Fitness Motivation",
  not_proud: "Do Something You're Not Proud Of",
  reminder: "Need a Gentle Reminder",
  not_planned: "Have Something Not Go as Planned",
  bed: "Don't Want to Get Out of Bed",
  keep_going: "Need a Reason to Keep Going",
  weird: "Want to Hear Something Weird",
  time_zone: "Are in a Different Time Zone",
  story: "Want to Hear a Story",
  rough_week: "Have a Rough Week",
  bad_news: "Have Bad News",
  good_news: "Have Good News",
  let_down: "Know Someone Let You Down",
  hurt: "Are Hurt",
  too_much: "Feel Like Everything is Too Much",
  unappreciated: "Feel Unappreciated",
  anxious: "Are Anxious",
  scream: "Need to Scream",
  listen: "Need Someone to Listen",
  attention: "Need Attention",
  hungover: "Are Hungover",
  far_away: "Feel Far Away From Me",
  procrastinate: "Are Procrastinating",
  blue: "Feel Blue for No Reason",
  confused: "Are Confused",
  traits: "Want to Know My Favorite Traits of Yours",
  future: "Are Unsure About the Future",
  advice: "Need Advice",
  hold_back: "Are Holding Back",
  photos: "Want to See My Favorite Photos of Us",
  bad_mental: "Are Struggling with Your Mental Health",
  escape: "Need an Escape",
  cash: "Need Money",
  travel_alone: "Are Traveling Alone",
  crazy: "Feel Like I'm Driving You Crazy",
  stressed: "Are Stressed Out",
  op: "Feel Out of Place",
  change: "Need a Change",
  secret: "Want to Know a Secret",
  scared: "Are Scared",
  weather_gloom: "See Gloomy Weather",
  weather_beautiful: "See Beautiful Weather",
  not_yourself: "Don't Feel Like Yourself",
  bucket_list: "Need Bucket List Ideas",
  expectations: "Feel Like Reality is Not Meeting Your Expectations",
  focus: "Need to Focus",
  homesick: "Are Feeling Homesick",
  self_love: "Need Self-Love Tips",
  regret: "Are Feeling Regretful",
  reminder_strong: "Need a Reminder of How Strong You Are",
  grateful: "Need a Reason to be Grateful",
  distraction: "Need a Distraction",
  calm: "Need to Calm Down",
  grief: "Are Grieving",
  three_am: "Can't Sleep at 3 AM and You're Thoughts are Racing",
  pretend: "Need to Pretend Everything is Okay",
  book: "Need Book Recommendations",
  idk_life: "Don't Know What to Do with Your Life",
  quit_habit: "Need to Quit a Bad Habit",
  never_say_never: "Do Something You Never Thought You'd be Able to Do",
  no_plans: "Have No Plans",
  poem: "Need a Poem About Yourself",
  no_talk: "Don't Feel Like Talking",
  never_knew: "Want to Know Something You Never Knew About Me",
  lucky: "Feel Lucky",
  finish: "Finish Reading All the Others",
  wynm: "When You Need Me",
};

const messages = {
    sad: "Hey love, I know you're feeling down right now. Just remember, you're never alone. I'm always here for you. ❤️",
    stressed: "Take a deep breath. You’ve got this! No matter what, I believe in you. 💪",
    insecure: "You are more than enough, just the way you are. I love you for YOU. 🌟",
    tired: "I wish I could be there to hug you right now. Rest, recharge, and know that I love you. 😘",
    happy: "Seeing you happy makes my day! Keep smiling, my love. 😊",
  };
  
export { messages, when_you };