const when_you = {
  first_read: "First Read Me",
  bad_day: "Have a Bad Day",
  miss_me: "Miss Me",
  need_laugh: "Need to Laugh",
  cannot_sleep: "Can't Sleep",
  feel_insecure: "are Feeling Insecure",
  feel_happy: "Are Happy",
  feel_lonely: "Feel Lonely",
  feel_worried: "Are Worried About Something",
  pep_talk: "Need a Pep Talk",
  happy_birthday: "Have a Birthday",
  merry_christmas: "Have a Merry Christmas",
  valentines_day: "Have a Happy Valentine's Day",
  new_year: "Have a Happy New Year",
  give_up: "Feel Like Giving Up",
  frustrated_with_work: "Are Frustrated with Work",
  sick: "Are Sick",
  plans_canceled: "See Our Plans Canceled",
  doubt_yourself: "Doubt Yourself",
  need_hug: "Need a Hug",
  need_compliment: "Need a Compliment",
  made_mistake: "Have Made a Mistake",
  need_motivation: "Need Motivation",
  need_movie_recomms: "Need Movie Recommendations",
  feel_excited: "Are Excited About Something",
  feel_bored: "Are Bored",
  make_big_decision: "Need to Make a Big Decision",
  sick_of_social_media: "Are Sick of Social Media",
  feel_angry: "Are Angry",
  heart_broken: "Get Your Heart Broken",
  argument_with_me: "Are in an Argument with Me",
  favorite_memory: "Want to Know My Favorite Memory of Us",
  no_speak: "Haven't Spoken to Me in a While",
  no_phone: "See Me Not Answering My Phone",
  give_up_on_goals: "Feel Like Giving Up on Your Goals",
  feel_embarass: "Do Something Embarrassing",
  lose_something_precious: "Lose Someone or Something Precious To You",
  presence: "Wish I Was There",
  feel_lik_crying: "Feel Like Crying",
  something_proud: "Do Something You're Proud Of",
  want_reminisce: "Want to Reminisce",
  need_loved: "Need to Feel Loved",
  you_angry_at_me: "Are Angry at Me",
  me_angry_at_you: "See Me Angry at You",
  something_new: "Do Something New",
  happy_anniversary: "Know It's Our Anniversary",
  celebrate_achievement: "Are Celebrating an Achievement",
  need_music_recomms: "Need Music Recommendations",
  special_occasion_without_me: "Have a Special Occasion I can't Attend",
  things_that_remind_me_of_you: "Want to Learn About the Things that Remind Me of You",
  need_food_recomms: "Need Food Recommendations",
  need_vacation: "Need a Vacation",
  need_fitness_motivation: "Need Fitness Motivation",
  something_not_proud: "Do Something You're Not Proud Of",
  gentle_reminder: "Need a Gentle Reminder",
  not_planned: "Have Something Not Go as Planned",
  bed_ridden: "Don't Want to Get Out of Bed",
  need_reason_to_keep_going: "Need a Reason to Keep Going",
  want_weird: "Want to Hear Something Weird",
  different_time_zone: "Are in a Different Time Zone",
  want_story: "Want to Hear a Story",
  have_rough_week: "Have a Rough Week",
  have_bad_news: "Have Bad News",
  have_good_news: "Have Good News",
  someone_let_down: "Know Someone Let You Down",
  feel_hurt: "Are Hurt",
  feel_overwhelmed: "Feel Like Everything is Too Much",
  feel_unappreciated: "Feel Unappreciated",
  feel_anxious: "Are Anxious",
  need_scream: "Need to Scream",
  need_listen: "Need Someone to Listen",
  need_attention: "Need Attention",
  feel_hungover: "Are Hungover",
  far_away_from_me: "Feel Far Away From Me",
  procrastination: "Are Procrastinating",
  feel_blue: "Feel Blue for No Reason",
  feel_confused: "Are Confused",
  favorite_traits: "Want to Know My Favorite Traits of Yours",
  unsure_of_future: "Are Unsure About the Future",
  need_advice: "Need Advice",
  holding_back: "Are Holding Back",
  favorite_photos: "Want to See My Favorite Photos of Us",
  bad_mental_health: "Are Struggling with Your Mental Health",
  need_escape: "Need an Escape",
  need_cash: "Need Money",
  travel_alone: "Are Traveling Alone",
  I_drive_you_crazy: "Feel Like I'm Driving You Crazy",
  feel_stressed_out: "Are Stressed Out",
  feel_out_of_place: "Feel Out of Place",
  need_change: "Need a Change",
  want_secret: "Want to Know a Secret",
  feel_scared: "Are Scared",
  weather_gloom: "See Gloomy Weather",
  weather_beautiful: "See Beautiful Weather",
  feel_not_yourself: "Don't Feel Like Yourself",
  bucket_list_ideas: "Need Bucket List Ideas",
  not_meeting_expectations: "Feel Like Reality is Not Meeting Your Expectations",
  need_focus: "Need to Focus",
  feel_homesick: "Are Feeling Homesick",
  need_self_love: "Need Self-Love Tips",
  feel_regret: "Are Feeling Regretful",
  reminder_youre_strong: "Need a Reminder of How Strong You Are",
  reason_grateful: "Need a Reason to be Grateful",
  need_distraction: "Need a Distraction",
  need_calm: "Need to Calm Down",
  feel_grief: "Are Grieving",
  three_am: "Can't Sleep at 3 AM and You're Thoughts are Racing",
  pretend_youre_okay: "Need to Pretend Everything is Okay",
  need_book_recomms: "Need Book Recommendations",
  idk_about_life: "Don't Know What to Do with Your Life",
  quit_bad_habit: "Need to Quit a Bad Habit",
  never_say_never: "Do Something You Never Thought You'd be Able to Do",
  have_no_plans: "Have No Plans",
  poem: "Need a Poem About Yourself",
  no_need_talk: "Don't Feel Like Talking",
  never_knew: "Want to Know Something You Never Knew About Me",
  feel_lucky: "Feel Lucky",
  finish_reading: "Finish Reading All the Others",
  need_me: "Need Me",
};

const messages = {
    sad: "Hey love, I know you're feeling down right now. Just remember, you're never alone. I'm always here for you. ❤️",
    stressed: "Take a deep breath. You’ve got this! No matter what, I believe in you. 💪",
    insecure: "You are more than enough, just the way you are. I love you for YOU. 🌟",
    tired: "I wish I could be there to hug you right now. Rest, recharge, and know that I love you. 😘",
    happy: "Seeing you happy makes my day! Keep smiling, my love. 😊",
  };
  
export { messages, when_you };